name: ocx-schema-parser
channels:
  - conda-forge
  - msys2 # for m2-grep
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.10
  - typer
  - loguru
  - rich
  - tqdm
  - tabulate
  # Dev deps
  - pip
  - poetry
  - pre-commit
  - tbump
  # Doc deps
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - sphinx-click
  - m2w64-make # GNU mMake for windows
  - m2-grep # Grep for windows. For Makefile sh
  - m2-gawk # awk for windows. for Makefile sh
  # Build & test
  - pytest
  # Install any PyPi packages
  - pip:
      # Packages only on PyPi
      - xsdata[cli,lxml,soap]
      - click-shell==2.1 # conda has not version 2.1
      - sphinx_automodapi
      - typer[all]
