name: ocx-schema-parser
channels:
  - conda-forge
  - msys2 # for m2-grep
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - poetry
  - pycurl
  - m2w64-make # GNU mMake for windows
  - m2-grep # Grep for windows. For Makefile sh
  - m2-gawk # awk for windows. for Makefile sh
  - pip:
      - xsdata[cli,lxml, soap]==23.8  # xsdata with all dependencies
      - poetry-plugin-export
